---
title: "publications"
output:
  distill::distill_article:
    toc: true
    toc_depth: 3
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

(pdfs of all papers can be downloaded from here)

## Peer-reviewed

### 2022

Azevedo, F., Lui, M., Pennington, C., Pownall, M., Evans, T., **Parsons, S.**, Elsherif, M., Micheli, L., Westwood, S., & Framework for Open and Reproducible Research Training (FORRT). (2022). Towards a culture of open scholarship: the role of pedagogical communities. *BMC Research Notes, 15*, 75. [doi.org/10.1186/s13104-022-05944-1](https://doi.org/10.1186/s13104-022-05944-1)   [<i class="fas fa-download"></i> PDF](papers/23_Azevedo_etal_2022_BMCResearchNotes.pdf)

<aside>
<div data-badge-type="donut" data-doi="10.1186/s13104-022-05944-1" data-hide-no-mentions="true" class="altmetric-embed"></div>
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
</aside>

**Parsons, S.**, Azevedo, F., Elsherif, M. M. M., Guay, S., ... & Aczel, B. (2022) A Community-Sourced Glossary of Open Scholarship Terms. *Nature Human Behavior*. [doi.org/10.1038/s41562-021-01269-4](https://doi.org/10.1038/s41562-021-01269-4). preprint: [osf.io/preprints/metaarxiv/kdqcw](https://osf.io/preprints/metaarxiv/kdqcw). Open access link: [rdcu.be/cHsqM](rdcu.be/cHsqM). website: [forrt.org/glossary/](https://forrt.org/glossary/)   [<i class="fas fa-download"></i> PDF](papers/22_Parsons_etal_2022_NatureHumanBehaviour.pdf)

<aside>
<div data-badge-type="donut" data-doi="10.1038/s41562-021-01269-4" data-hide-no-mentions="true" class="altmetric-embed"></div>
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
</aside>

**Parsons, S.**, Todorovic, A., Lim, M., Songco, A., & Fox, E. (2022). Data and protocol for the Oxford Achieving Resilience during COVID-19 (ARC) study. *Journal of Open Psychology Data  10(1)*, 4. [doi.org/10.5334/jopd.56](http://doi.org/10.5334/jopd.56)   [<i class="fas fa-download"></i> PDF](papers/21_Parsons_etal_2022_JournalofOpenPsychologyData.pdf)

<aside>
<div data-badge-type="donut" data-doi="10.5334/jopd.56" data-hide-no-mentions="true" class="altmetric-embed"></div>
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
</aside>

**Parsons, S** (2020). Exploring reliability heterogeneity with multiverse analyses: Data processing decisions unpredictably influence measurement reliability. *accepted for publication at Meta-Psychology*. Preprint: [psyarxiv.com/y6tcz](https:/psyarxiv.com/y6tcz), data and code: [osf.io/haz6u/](https://osf.io/haz6u/)   [<i class="fas fa-download"></i> PDF](papers/20_Parsons_2022_MetaPsychology_acceptedpreprint.pdf)

<aside>
<div data-badge-type="donut" data-doi="10.31234/osf.io/y6tcz" data-hide-no-mentions="true" class="altmetric-embed"></div>
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
</aside>

### 2021

Pownall, M., Azevedo, F., Aldoh, A., Elsherif, M. Vasilev, M., Pennington, C., Robertson, O., Vel Tromp, M., Lui, M., Makel, M., Tonge, N., Moreau, D., Horry, R., Shaw, J., Tzavella, L., McGarrigle, R., Talbot, C., **Parsons, S.*, & FORRT (2021). Embedding open and reproducible science into teaching: A bank of lesson plans and resources.  *Scholarship of Teaching and Learning in Psychology*. [doi.org/10.1037/stl0000307](https://doi.org/10.1037/stl0000307)   [<i class="fas fa-download"></i> PDF](papers/19_Pownall_etal_2021_ScholarshipofTeachingandLearninginPsychology.pdf)

<aside>
<div data-badge-type="donut" data-doi="10.1037/stl0000307" data-hide-no-mentions="true" class="altmetric-embed"></div>
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
</aside>

Lim, M. C., **Parsons, S.**, Goglio, A., & Fox, E. (2021). Anxiety, stress, and binge eating behaviours in adolescence: a prospective approach. *Journal of Eating Disorders, 9*. [doi.org/10.1186/s40337-021-00444-2](https://doi.org/10.1186/s40337-021-00444-2)    [<i class="fas fa-download"></i> PDF](papers/18_Lim_Parsons_Goglio_Fox_2021_JournalofEatingDisorders.pdf)

<aside>
<div data-badge-type="donut" data-doi="10.1186/s40337-021-00444-2" data-hide-no-mentions="true" class="altmetric-embed"></div>
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
</aside>

**Parsons, S.**, (2021). splithalf: robust estimates of split half reliability. *Journal of Open Source Software, 6*(60), 3041, [doi.org/10.21105/joss.03041](https://doi.org/10.21105/joss.03041)   [<i class="fas fa-download"></i> PDF](papers/17_Parsons_2021_JournalofOpenSourceSoftware.pdf)

<aside>
<div data-badge-type="donut" data-doi="10.21105/joss.03041" data-hide-no-mentions="true" class="altmetric-embed"></div>
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
</aside>

**Parsons, S.**, Booth, C., Songco, A., & Fox, E. (2021). Emotional information-processing correlates of mental health in adolescence: A network analysis approach. *Cognition and Emotion* \\ [doi.org/10.1080/02699931.2021.1915752](https://doi.org/10.1080/02699931.2021.1915752). Preprint: [psyarxiv.com/8ygn](https://psyarxiv.com/8ygnh), data and code: [osf.io/mn5ek/](https://osf.io/mn5ek/)    [<i class="fas fa-download"></i> PDF](papers/16_Parsons_etal_2021_CognitionandEmotion.pdf)

<aside>
<div data-badge-type="donut" data-doi="10.1080/02699931.2021.1915752" data-hide-no-mentions="true" class="altmetric-embed"></div>
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
</aside>

Demkowicz, O., Panayiotou, M., **Parsons, S.**, Feltham, A., Arseneault, L., Ingram, B., Patalay, P., Edge D.,, Pierce, M., Creswell, C., Victor, C., O'Connor, R., & Qualter, P. (2021). Looking back to move forward: Reflections on the strengths and challenges of the COVID-19 UK mental health research response. 
*Frontiers Psychiatry*. [10.3389/fpsyt.2021.622562](https://doi.org/10.3389/fpsyt.2021.622562)   [<i class="fas fa-download"></i> PDF](papers/15_Demkowicz_etal_2021_FrontiersPsychiatry.pdf)

<aside>
<div data-badge-type="donut" data-doi="10.3389/fpsyt.2021.622562" data-hide-no-mentions="true" class="altmetric-embed"></div>
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
</aside>

### 2020

Songco, A., Booth, C., Spiegler, O., **Parsons, S.**, & Fox, E. (2020). Anxiety and depressive symptom trajectories in adolescence and the co-occurring development of cognitive biases: Evidence from the CogBIAS longitudinal study. *Journal of Abnormal Child Psychology, 48*, 1617–1633, DOI: [10.1007/s10802-020-00694-9](https://doi.org/10.1007/s10802-020-00694-9)    [<i class="fas fa-download"></i> PDF](papers/14_Songco_etal_2020_JournalofAbnormalChildPsychology.pdf)

<aside>
<div data-badge-type="donut" data-doi="10.1007/s10802-020-00694-9" data-hide-no-mentions="true" class="altmetric-embed"></div>
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
</aside>

Booth, C., Songco, A., **Parsons, S.**, & Fox, E. (2020). Cognitive mechanisms predicting resilient functioning in adolescence: Evidence from the CogBIAS longitudinal study. *Development and Psychopathology*, 1-9. DOI: [10.1017/S0954579420000668](https://doi.org/10.1017/S0954579420000668)   [<i class="fas fa-download"></i> PDF](papers/13_Booth_etal_2020_DevelopmentandPsychopathology.pdf)

<aside>
<div data-badge-type="donut" data-doi="10.1017/S0954579420000668" data-hide-no-mentions="true" class="altmetric-embed"></div>
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
</aside>

Dodd, H., Rayson, H., Ryan, Z., Bishop, C., **Parsons, S.**, Stuijfzand, B. (2020). Trajectories of anxiety when children start school: The role of behavioral inhibition and attention bias to angry and happy faces
*Journal of Abnormal Psychology*. DOI: [10.1037/abn0000623](https://doi.org/10.1037/abn0000623)   [<i class="fas fa-download"></i> PDF](papers/12_Dodd_etal_2020_JournalofAbnormalPsychology.pdf)

<aside>
<div data-badge-type="donut" data-doi="10.1037/abn0000623" data-hide-no-mentions="true" class="altmetric-embed"></div>
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
</aside>

**Parsons, S.** (2020). Does attention bias modification induce structural brain changes? A commentary on Abend et al. (2019). *Biological Psychology, 152*. DOI: [10.1016/j.biopsycho.2020.107866](https://www.sciencedirect.com/science/article/pii/S0301051120300260). Preprint: [psyarxiv.com/4ze6h](https://psyarxiv.com/4ze6h/)   [<i class="fas fa-download"></i> PDF](papers/11_Parsons_2020_BiologicalPsychiatry.pdf)

<aside>
<div data-badge-type="donut" data-doi="10.1016/j.biopsycho.2020.107866" data-hide-no-mentions="true" class="altmetric-embed"></div>
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
</aside>

### 2019

Herbert, M., Notebaert, L., **Parsons, S.**, Fox, E., & MacLeod, C. (2019). The Effect of Varying Danger Controllability on Attention to Threat Messages. *Applied Cognitive Psychology, 34*(2). DOI: [10.1002/acp.3628](https://onlinelibrary.wiley.com/doi/abs/10.1002/acp.3628)   [<i class="fas fa-download"></i> PDF](papers/10_Herbert_etal_2019_AppliedCognitivePsychology.pdf)

<aside>
<div data-badge-type="donut" data-doi="10.1002/acp.3628" data-hide-no-mentions="true" class="altmetric-embed"></div>
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
</aside>

**Parsons, S.**, Kruijt, A-W., & Fox, E. (2019). Psychological Science needs a standard practice of reporting the reliability of cognitive behavioural measurements. *Advances in Methods and Practices in Psychological Science, 2,*(4), 378-395. DOI: [doi.org/10.1177/2515245919879695](https://doi.org/10.1177/2515245919879695). Preprint: [psyarxiv.com/6ka9z](https://psyarxiv.com/6ka9z)   [<i class="fas fa-download"></i> PDF](papers/9_Parsons_Kruijt_Fox_2019_AMPPS.pdf)

<aside>
<div data-badge-type="donut" data-doi="10.1177/2515245919879695" data-hide-no-mentions="true" class="altmetric-embed"></div>
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
</aside>

Booth, C., Songco, A., **Parsons, S.**, Heathcote, L.C., & Fox, E. (2019). The CogBIAS longitudinal study of adolescence: Cohort profile and stability and change in measures across three waves. *BMC Psychology, 7*, 73. DOI: [10.1186/s40359-019-0342-8](https://bmcpsychology.biomedcentral.com/articles/10.1186/s40359-019-0342-8)   [<i class="fas fa-download"></i> PDF](papers/8_Booth_etal_2019_BMCPsychology.pdf)

<aside>
<div data-badge-type="donut" data-doi="10.1186/s40359-019-0342-8" data-hide-no-mentions="true" class="altmetric-embed"></div>
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
</aside>

Crüwell, S., van Doorn, J., Etz, A., Makel, M.C., Moshontz, H., Niebaum, J., Orben, A., **Parsons, S.**, & Schulte-Mecklenbeck, M. (2019). 7 Easy Steps to Open Science: An annotated reading list. *Zeitschrift für Psychologie, 227*, 237-248. DOI: [doi.org/10.1027/2151-2604/a000387](https://doi.org/10.1027/2151-2604/a000387). Preprint: [psyarxiv.com/cfzyx](https://psyarxiv.com/cfzyx)   [<i class="fas fa-download"></i> PDF](papers/7_Cruwell_etal_2019_ZeitschriftfürPsychologie.pdf)

<aside>
<div data-badge-type="donut" data-doi="10.1027/2151-2604/a000387" data-hide-no-mentions="true" class="altmetric-embed"></div>
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
</aside>

Kruijt, A-W., **Parsons, S.**, & Fox, E. (2019). A meta-analysis of bias at baseline in RCTs of attention bias modification: no evidence for bias towards threat in clinical anxiety and PTSD. *Journal of Abnormal Psychology, 128*(6), 563-573. DOI: 10.1037/abn0000406. Preprint DOI: [10.31234/osf.io/rfjup](10.31234/osf.io/rfjup)   [<i class="fas fa-download"></i> PDF](papers/6_Kruijt_Parsons_Fox_2019_JournalAbnormalPsychology.pdf)

<aside>
<div data-badge-type="donut" data-doi="10.1037/abn0000406" data-hide-no-mentions="true" class="altmetric-embed"></div>
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
</aside>

### 2018

**Parsons, S.** (2018). Moving forward with questions of process and procedure in cognitive bias modification research: three points of consideration. *Published as an eLetter on* [10.1192/bjp.2018.43](https://doi.org/10.1192/bjp.2018.43). Preprint: [psyarxiv.com/k3vxc](https://psyarxiv.com/k3vxc)   [<i class="fas fa-download"></i> PDF](papers/5_Parsons_2018_BritishJournalPsychiatryeLetter.pdf)

<aside>
<div data-badge-type="donut" data-doi="10.1192/bjp.2018.43" data-hide-no-mentions="true" class="altmetric-embed"></div>
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
</aside>

Notebaert, L., Georgiades, J., Herbert, M., Grafton, B., **Parsons, S.**, Fox, E., & MacLeod, C. (2018). Trait anxiety and the alignment of attentional bias with controllability of danger. *Psychological Research*. DOI: [doi.org/10.1007/s00426-018-1081-9](https://doi.org/10.1007/s00426-018-1081-9)   [<i class="fas fa-download"></i> PDF](papers/4_Notebaert_etal_2018_PsychologicalResearch.pdf)

<aside>
<div data-badge-type="donut" data-doi="10.1007/s00426-018-1081-9" data-hide-no-mentions="true" class="altmetric-embed"></div>
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
</aside>

### 2017

Lakens, et al. (2017). Justify Your Alpha: A Response to “Redefine Statistical Significance”. *Nature Human Behaviour, 2*, 168-171. DOI: [10.1038/s41562-018-0311-x](https://www.nature.com/articles/s41562-018-0311-x). Preprint: [psyarxiv.com/9s3y6/](https://psyarxiv.com/9s3y6/)   [<i class="fas fa-download"></i> PDF](papers/3_Lakens_etal_2017_NatureHumanBehavior.pdf)

<aside>
<div data-badge-type="donut" data-doi="10.1038/s41562-018-0311-x" data-hide-no-mentions="true" class="altmetric-embed"></div>
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
</aside>

Booth, C., Songco, A., **Parsons, S.**, Heathcote, L., Vincent, J., Keers, R., & Fox, E. (2017). The CogBIAS longitudinal study protocol: cognitive and genetic factors influencing psychological functioning in adolescence. *BMC Psychology, 5*(1). DOI: [doi.org/10.1186/s40359-017-0210-3](https://doi.org/10.1186/s40359-017-0210-3)   [<i class="fas fa-download"></i> PDF](papers/2_Booth_etal_2017_BMCPsychology.pdf)

<aside>
<div data-badge-type="donut" data-doi="10.1186/s40359-017-0210-3" data-hide-no-mentions="true" class="altmetric-embed"></div>
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
</aside>

### 2016

**Parsons, S**, Kruijt, A-W., & Fox, E. (2016). A cognitive model of psychological resilience. *Journal of Experimental Psychopathology, 7*(3), 296-310. DOI: [10.5127/jep.053415](http://dx.doi.org/10.5127/jep.053415)   [<i class="fas fa-download"></i> PDF](papers/1_Parsons_Kruijt_Fox_2016_JournalExperimentalPsychopathology.pdf)

<aside>
<div data-badge-type="donut" data-doi="10.5127/jep.053415" data-hide-no-mentions="true" class="altmetric-embed"></div>
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
</aside>

## Preprints and working papers

FORRT. (2019). Introducing a Framework for Open and Reproducible Research Training (FORRT). (Co-author). Preprint: [osf.io/bnh7p/](https://osf.io/bnh7p/). Website: [forrt.org](https://forrt.org)

**Parsons, S** (2019). Visualising two approaches to explore reliability-power relationships. Preprint: [psyarxiv.com/qh5mf](https://psyarxiv.com/qh5mf)