---
title: "Bye Hugo Academic, hello Distill for Rmarkdown"
description: |
  Why I gave up on Hugo Academic
author:
  - name: Sam Parsons
    url: 
date: 09-29-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

I grew to dislike Hugo Academic for building my website. To start this website, I thought I'd share some reflections on the transition to [Distill](https://rstudio.github.io/distill/).

## Why does Hugo hate me?

I loved it at first. Relatively easy to set up, nice formatting, works on Rmarkdown. Lots of positives. 

Some months passed, and I needed to update papers. Nothing too problematic, but; copying a folder, entering all of the pieces of information, and finally completing new entries always took longer than I would like. Compared to my CV in overleaf, I can add new presentations and papers in 30 seconds, easy. 

Added to this, every time there was a non-trivial update to any of R, blogdown, Hugo, something with netlify, or some combination of the way these things interact tended to break everything. Not to mention the transition to wowchemy. Every time this happened, the "easiest" thing to do was to rebuild the entire site. 

Rebuilding the site was a) not fun, b) time consuming, and c) misses my main goal of having an easily update-able website. I want to make changes, build the site, and then push to github. I want to not enter rage every time. 

I almost remade it again recently. I'm glad I searched for alternatives and, luckily, spotted a few nice website/blogs. They used distill

## Distill is less complicated

One of the first things I read was that there were fewer dependencies on other things, including, including themes, hugo, and netlify. 

I still slightly prefer the Hugo Academic theme, but a simpler theme for less hassle is more than worth it. Personally, I'm liking that I can link my CV and not feel compelled to add every poster and presentation I have given to the website itself (not that you cant, but because it's not there by default you dont feel bad about not doing so)


## A few tips I came across or learned:

1. add the following to your theme.css file to use academic icons:
`@import url('https://cdn.rawgit.com/jpswalsh/academicons/master/css/academicons.min.css');`
You can then call the icons with something like the following (remember to replace the `fab` and `fa` with `ai`):
`<i class="ai ai-osf"></i>`

2. you can add a few themes with **postcards**, I kind of like not having too many options. You can do way more with css and html, but I want simplicity and efficiency in my life at the moment. 

3. Adding altmertic badges is pretty easy, you can just add something like the following, copied from the [altmetric website](https://www.altmetric.com/products/altmetric-badges/)
<div data-badge-type="donut" data-doi="10.21105/joss.03041" data-hide-no-mentions="true" class="altmetric-embed"></div>

But, you'll likely also need to add the following so that it works ([from here](https://stackoverflow.com/questions/48883164/altmetric-badge-not-showing-in-rmarkdown-document/48905134))

<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>